export const page = `<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>NetDownloader</title>
  <style>
    :root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;color:#e9edf5;background:#0c1018}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 75% 0%,#182d41 0%,#0c1018 50%)}
    main{max-width:980px;margin:auto;padding:48px 20px 80px}header{margin-bottom:40px}.eyebrow{color:#73e0c0;letter-spacing:.16em;text-transform:uppercase;font-size:12px;font-weight:700}h1{font-size:clamp(36px,6vw,64px);line-height:1.05;letter-spacing:-.055em;margin:10px 0 14px}header p{color:#a8b3c3;max-width:620px;line-height:1.6}
    .panel{background:#151c28;border:1px solid #283447;border-radius:20px;padding:24px;margin:20px 0;box-shadow:0 12px 34px #0003}h2{font-size:19px;margin:0 0 18px;letter-spacing:-.02em}form{display:flex;gap:10px}input,select{min-width:0;background:#0b111b;color:#fff;border:1px solid #384658;border-radius:11px;padding:13px 15px;font:inherit;outline:none}input{flex:1}input:focus,select:focus{border-color:#79e7c6}button,.button{border:0;border-radius:11px;background:#75e0c0;color:#06251d;font:inherit;font-weight:700;padding:12px 18px;cursor:pointer;white-space:nowrap;text-decoration:none;display:inline-block}button:hover,.button:hover{background:#a2f0d7}button:disabled{opacity:.5;cursor:wait}.hint{color:#91a0b2;font-size:13px;line-height:1.5;margin:12px 0 0}.error{color:#ff9b9b}.results{display:grid;gap:12px;margin-top:20px}.result{border:1px solid #2c3b4e;border-radius:13px;padding:14px;display:flex;gap:15px;align-items:center;background:#101722}.thumb{width:126px;height:75px;object-fit:cover;border-radius:8px;background:#283447;flex-shrink:0}.result-body{min-width:0;flex:1}.result strong{display:block;line-height:1.35}.meta{font-size:12px;color:#8ea5b6;margin:5px 0}.result p{color:#a8b3c3;font-size:13px;line-height:1.4;margin:4px 0 0;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.result button{font-size:13px;padding:9px 12px}.job{border-left:3px solid #75e0c0;padding:8px 0 8px 14px;margin-top:12px}.job p{margin:5px 0;color:#a8b3c3;font-size:14px}.job a{color:#75e0c0}.empty{color:#93a5b6;padding:18px 0}@media(max-width:640px){main{padding-top:32px}form{flex-direction:column}.result{align-items:flex-start}.thumb{width:88px;height:66px}.result button{align-self:center}.result p{display:none}}
  </style>
</head>
<body><main>
  <header><span class="eyebrow">Busca e download de vídeos</span><h1>Encontre. Escolha.<br>Baixe.</h1><p>Pesquise vídeos em várias plataformas ou cole o link de um vídeo público. O processamento acontece no GitHub Actions; o arquivo fica disponível aqui quando terminar.</p></header>
  <section class="panel"><h2>Pesquisar vídeos</h2><form id="search-form"><input id="query" type="search" placeholder="Ex.: receita de pão de queijo" required maxlength="200" autocomplete="off"><select id="search-source" aria-label="Fonte da busca"><option value="youtube">YouTube (sem chave)</option><option value="web">Web (Brave)</option></select><button id="search-button">Pesquisar</button></form><div id="search-message" class="hint">A busca no YouTube usa o GitHub Actions e pode levar alguns minutos. A busca na Web usa a Brave.</div><div id="results" class="results"></div></section>
  <section class="panel"><h2>Baixar pelo link</h2><form id="url-form"><input id="video-url" type="url" placeholder="https://www.youtube.com/watch?v=..." required maxlength="2000"><button id="url-button">Baixar vídeo</button></form><p class="hint">Links HTTPS públicos. O suporte depende do site e pode mudar.</p></section>
  <section class="panel"><h2>Downloads</h2><div id="jobs"><p class="empty">Nenhum download nesta sessão.</p></div></section>
</main>
<script>
const jobsEl=document.querySelector('#jobs');
const activeJobs=new Map();
async function api(path,options){const response=await fetch(path,options);let data;try{data=await response.json()}catch{throw new Error('Resposta inesperada do servidor.')}if(!response.ok)throw new Error(data.error||'Falha na solicitação.');return data}
function el(tag,cls,text){const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node}
function setMessage(message,error=false){const node=document.querySelector('#search-message');node.textContent=message;node.className=error?'hint error':'hint'}
function savedJobs(){try{return JSON.parse(localStorage.getItem('netdownloader-jobs')||'[]')}catch{return []}}
function addJob(data,url,restore=false){const empty=jobsEl.querySelector('.empty');if(empty)empty.remove();const box=el('div','job');const title=el('strong','',url);title.style.overflowWrap='anywhere';const status=el('p','','Aguardando início…');const links=el('div');const github=el('a','','Ver execução');github.href=data.github_url;github.target='_blank';github.rel='noopener noreferrer';links.append(github);box.append(title,status,links);jobsEl.prepend(box);activeJobs.set(data.id,{status,links});if(!restore){try{localStorage.setItem('netdownloader-jobs',JSON.stringify([{id:data.id,github_url:data.github_url,url},...savedJobs()].slice(0,20)))}catch{}}poll(data.id)}
async function poll(id){const view=activeJobs.get(id);if(!view)return;try{const data=await api('/api/jobs/'+id);if(data.status==='completed'){if(data.conclusion==='success'&&data.artifact){view.status.textContent='Concluído. Arquivo disponível em ZIP ('+Math.round(data.artifact.size/1048576)+' MB).';const link=el('a','button','Baixar arquivo');link.href=data.artifact.download_url;link.style.margin='10px 0 0';view.links.append(link)}else view.status.textContent='Falhou ou foi cancelado. Abra a execução para ver o erro.';activeJobs.delete(id);return}view.status.textContent=data.status==='in_progress'?'Baixando e preparando o arquivo…':'Na fila do GitHub Actions…'}catch(error){view.status.textContent=error.message}setTimeout(()=>poll(id),5000)}
async function start(url,button){button.disabled=true;try{const data=await api('/api/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})});addJob(data,url)}catch(error){alert(error.message)}finally{button.disabled=false}}
document.querySelector('#url-form').addEventListener('submit',event=>{event.preventDefault();const input=document.querySelector('#video-url');start(input.value.trim(),document.querySelector('#url-button'))});
function showResults(results){const list=document.querySelector('#results');list.replaceChildren();setMessage(results.length+' resultado(s) encontrado(s).');for(const item of results){const card=el('div','result');if(item.thumbnail){const img=el('img','thumb');img.src=item.thumbnail;img.alt='';img.loading='lazy';card.append(img)}const body=el('div','result-body');body.append(el('strong','',item.title),el('div','meta',[item.source,item.duration].filter(Boolean).join(' · ')),el('p','',item.description));const button=el('button','','Baixar');button.type='button';button.addEventListener('click',()=>start(item.url,button));card.append(body,button);list.append(card)}}
async function pollSearch(id){for(let attempt=0;attempt<120;attempt++){await new Promise(resolve=>setTimeout(resolve,5000));const data=await api('/api/search/jobs/'+id);if(data.status==='completed'){if(data.conclusion!=='success')throw new Error('A busca falhou. Veja a execução no GitHub Actions.');showResults(data.results||[]);return}setMessage('Busca no GitHub Actions: '+(data.status==='in_progress'?'pesquisando…':'aguardando na fila…'))}throw new Error('A busca demorou demais. Tente novamente.')}
document.querySelector('#search-form').addEventListener('submit',async event=>{event.preventDefault();const query=document.querySelector('#query').value.trim();const source=document.querySelector('#search-source').value;const button=document.querySelector('#search-button');button.disabled=true;document.querySelector('#results').replaceChildren();setMessage('Pesquisando…');try{const data=await api('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({q:query,source})});if(data.results)showResults(data.results);else await pollSearch(data.id)}catch(error){setMessage(error.message,true)}finally{button.disabled=false}});
for(const job of savedJobs().reverse())if(Number.isSafeInteger(job.id)&&typeof job.url==='string'&&typeof job.github_url==='string')addJob(job,job.url,true);
</script></body></html>`;
